language: java
jdk: oraclejdk8
#branches:
#  only:
#    - master
#    - develop
sudo: false
before_install:
  - echo "installing private repository"
  - git clone $PRIVATE_REPO_URL_UN_PW jpo-ode-private 
  - cd jpo-ode-private
  - mvn clean
  - mvn install
  - cd ..
install: true #must disable pre-installation of dependencies because it fails due to missing oss.runtime dependency install 
addons:
  sonarqube:
    token:
      secure: $SONAR_SECURITY_TOKEN
    branches:
       - /.*/
      - master
      - develop
      - refactor
script:
  - mvn clean
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
