language: java

dist: trusty

jdk: oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: "usdot-jpo-ode"
    token:
      secure: $SONAR_SECURITY_TOKEN_NEW
    branches:
      - .*

script:
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache: false
